language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-ng-bstrap-rjs' ]; then cd .. && eval "mv $currentfolder generator-ng-bstrap-rjs" && cd generator-ng-bstrap-rjs; fi
